FROM nginx:alpine
 
COPY nginx.conf /etc/nginx/conf.d/default.conf
 
COPY index.html /usr/share/nginx/html/
 
RUN addgroup -g 1001 -S nginx-user && \
    adduser -S nginx-user -u 1001 && \
    chown -R nginx-user:nginx-user /usr/share/nginx/html && \
    chown -R nginx-user:nginx-user /var/cache/nginx && \
    chown -R nginx-user:nginx-user /var/log/nginx && \
    touch /var/run/nginx.pid && \
    chown nginx-user:nginx-user /var/run/nginx.pid
 
EXPOSE 80
 
HEALTHCHECK --interval=30s --timeout=3s --start-period=5s --retries=3 \
  CMD wget --no-verbose --tries=1 --spider http://localhost || exit 1
 
USER nginx-user
 
CMD ["nginx", "-g", "daemon off;"]